name: "pedestrian_detection"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 16
input [
	{
		name: "images"
		data_type: TYPE_FP32
		format: FORMAT_NCHW
		dims: [3, 640, 640]
	}
]
output [
	{
		name: "output"
		data_type: TYPE_FP32
		dims: [-1, -1]
	}
]